template:
  - sensor:
    - name: "Solar Selfconsumption Ratio"
      unique_id: solar_selfconsumption_ratio
      icon: mdi:percent-outline
      state: >
        {% set panel_to_house_daily = states('sensor.solar_panel_to_house_daily') | float(0) %}
        {% set exported_power_daiy = states('sensor.solar_exported_power_daiy') | float(0) %}

        {% if (panel_to_house_daily + exported_power_daiy <= 0) %}
          0
        {% else %}
          {{ ((panel_to_house_daily) / (panel_to_house_daily + exported_power_daiy) * 100) | round (1) }}
        {% endif %}

    - name: "Solar Autarkie Ratio"
      unique_id: solar_autarkie_ratio
      icon: mdi:percent-outline
      state: >
        {% set house_consumption_daily = states('sensor.solar_house_consumption_daily') | float(0) %}
        {% set imported_power_daily = states('sensor.solar_imported_power_daily') | float(0) %}

        {% if (house_consumption_daily <= 0) %}
          0
        {% else %}
          {{ (1 - (imported_power_daily / house_consumption_daily) * 100) | round (1) }}
        {% endif %}

    - name: "Solar Inverter Effectiveness"
      unique_id: solar_inverter_effectiveness
      icon: mdi:percent-outline
      unit_of_measurement: "%"
      state: >
        {% set i1_dc_power = states('sensor.solaredge_i1_dc_power') | float(0) %}
        {% set i1_ac_power = states('sensor.solaredge_i1_ac_power') | float(0) %}
        {% set inverter_effectiveness = states('sensor.solar_inverter_effectiveness') %}

        {% if (is_state('sensor.solar_inverter_effectiveness', 'unknown')) %}
          1
        {% elif (i1_dc_power < 100 or i1_ac_power  < 100) %}
          {{ inverter_effectiveness }}
        {% else %}
          {{ (i1_ac_power ) / (i1_dc_power) }}
        {% endif %}
      availability: >
        {{ states('sensor.solaredge_i1_dc_power') | is_number and states('sensor.solaredge_i1_ac_power') | is_number }}        

    - name: "Solar Inverter Effectiveness Int"
      unique_id: solar_inverter_effectiveness_int
      icon: mdi:percent-outline
      unit_of_measurement: "%"
      state: >
        {{ ((states('sensor.solar_inverter_effectiveness') | float(0)) * 100) | round(2) }}

    - name: "Solar Inverter Effectiveness Average Int"
      unique_id: solar_inverter_effectiveness_average_int
      icon: mdi:percent-outline
      unit_of_measurement: "%"
      state: >
        {{ ((states('sensor.solar_inverter_effectiveness_average') | float(0)) * 100) | round(2) }}


sensor:
  - platform: statistics
    name: "Solar Inverter Effectiveness Average"
    unique_id: solar_inverter_effectiveness_average
    state_characteristic: mean
    sampling_size: 1200
    max_age:
      hours: 24
    entity_id: sensor.solar_inverter_effectiveness
